export default [
  {
    name: "Alaor",
    speciality: "MTB e Road bike",
    ridesWhere: "BH e Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/22001130",
  },
  {
    name: "Marciel",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/7839558",
  },
  {
    name: "Décio Otávio",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/22609925",
  },
  {
    name: "Kaio",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/8815128",
  },
  {
    name: "Alberto Sillas",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/22001086",
  },
  {
    name: "Carlos Eduardo (Dudu)",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/50325372",
  },
  {
    name: "Fernando",
    speciality: "MTB e Road bike",
    ridesWhere: "BH e Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/14476282",
  },
  {
    name: "Filipe",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/59920626",
  },
  {
    name: "Guilherme",
    speciality: "MTB e Road bike",
    ridesWhere: "Itapecerica e Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/8628339",
  },
  {
    name: "Joel Teixeira",
    speciality: "MTB",
    ridesWhere: "Cláudio e Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/44266589",
  },
  {
    name: "Lazinho",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/41379",
  },
  {
    name: "Luiz Henrique",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/25042339",
  },
  {
    name: "Pedro Henrique",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/50071667",
  },
  {
    name: "Rafael",
    speciality: "MTB",
    ridesWhere: "Cláudio e Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/37306308",
  },
  {
    name: "Weliton",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/25661992",
  },
  {
    name: "Wyllyam",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/38609777",
  },
  {
    name: "Silas Moreira",
    speciality: "MTB",
    ridesWhere: "BH, Minas Gerais",
    profile: "https://www.strava.com/athletes/49393837",
  },
  {
    name: "Fabiano",
    speciality: "MTB",
    ridesWhere: "Camacho, Minas Gerais",
    profile: "https://www.strava.com/athletes/39287052",
  },
];
